# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.BuildID)

trigger: none

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

variables:
  marketplace_publisher: 'jreleaser'
  marketplace_extensionName: 'JReleaser-EarlyAccess'
  marketplace_extensionId: 'jreleaser-azure-devops-extension-earlyaccess'
  marketplace_share_with: 'JReleaser'
  marketplace_share_with_author: 'shblue21'
  install_account: 'https://dev.azure.com/JReleaser'

stages:
- template: templates/publish-build-stage.yml

- template: templates/publish-vsix-stage.yml
  parameters:
    marketplacePublisher: $(marketplace_publisher)
    marketplaceExtensionName: $(marketplace_extensionName)
    marketplaceExtensionId: $(marketplace_extensionId)
    extensionVisibility: 'private'
    shareWith: '$(marketplace_share_with),$(marketplace_share_with_author)'
    unpublishFirst: true
    versionStrategy: 'earlyaccess'
