# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.BuildID)

trigger: none

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

variables:
  marketplace_publisher: 'jreleaser'
  marketplace_extensionName: 'JReleaser'
  marketplace_extensionId: 'jreleaser-azure-devops-extension'
  
stages:
- stage: Build
  jobs:
  - job: Build_JReleaser_Installer
    steps:
    - task: Npm@1
      displayName: 'install'
      inputs:
        command: install
        workingDir: $(System.DefaultWorkingDirectory)/tasks/JReleaserInstaller
    - task: Npm@1
      displayName: 'build'
      inputs:
        command: custom
        customCommand: 'run build'
        workingDir: $(System.DefaultWorkingDirectory)/tasks/JReleaserInstaller
    - task: CopyFiles@2
      displayName: 'copy'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/tasks/JReleaserInstaller/'
        Contents: |
          **/*
          !**/*.ts
          !Test/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: JReleaserInstaller

  - job: Build_JReleaser_Task
    steps:
    - task: Npm@1
      displayName: 'install'
      inputs:
        command: install
        workingDir: $(System.DefaultWorkingDirectory)/tasks/JReleaserTask
    - task: Npm@1
      displayName: 'build'
      inputs:
        command: custom
        customCommand: 'run build'
        workingDir: $(System.DefaultWorkingDirectory)/tasks/JReleaserTask
    - task: CopyFiles@2
      displayName: 'copy'
      inputs:
        sourceFolder: $(System.DefaultWorkingDirectory)/tasks/JReleaserTask/
        contents: |
          **/*
          !**/*.ts
          !Test/**
        targetFolder: $(Build.ArtifactStagingDirectory)
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: JReleaserTask

  - job: Build_JReleaser_Extension
    dependsOn: ['Build_JReleaser_Installer', 'Build_JReleaser_Task']
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download JReleaserInstaller'
      inputs:
        artifact: JReleaserInstaller
        path: $(System.DefaultWorkingDirectory)/tasks/JReleaserInstaller
    - task: DownloadPipelineArtifact@2
      displayName: 'Download JReleaserTask'
      inputs:
        artifact: JReleaserTask
        path: $(System.DefaultWorkingDirectory)/tasks/JReleaserTask
    - task: CopyFiles@2
      displayName: 'copy JReleaser Extension'
      inputs:
        contents: |
          **/*
          !**/*.ts
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: JReleaserExtension
- stage: Publish_JReleaser_Extension
  dependsOn: ['Build']
  jobs:
  - job: Publish_JReleaser_Extension
    steps:
    - checkout: self
      fetchTags: true
      clean: true
    - script: |
        if [[ "$(Build.SourceBranch)" != refs/tags/* ]]; then
          echo "Build was not triggered by a tag, exiting."
          exit 1
        fi
        version=${Build.SourceBranch#refs/tags/}
        echo "##vso[task.setvariable variable=version]$version"
    - task: DownloadPipelineArtifact@2
      displayName: 'Download JReleaserExtension'
      inputs:
        artifact: JReleaserExtension
        path: $(System.DefaultWorkingDirectory)
    - task: TfxInstaller@3
      displayName: 'install tfx-cli'
      inputs:
        version: '0.14.x'
        checkLatest: true
    - task: PackageAzureDevOpsExtension@4
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        patternManifest: 'jreleaser-azure-devops-extension.json'
        outputPath: 'jreleaser-azure-devops-extension.vsix'
        updateTasksVersion: false
        extensionName: '$(marketplace_extensionName)'
        extensionId: '$(marketplace_extensionId)'
        extensionVersion: '$(version)'
        extensionVisibility: 'public preview'
        extensionPricing: 'free'
    - task: PublishAzureDevOpsExtension@4
      name: publish
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'jreleaser_publish'
        fileType: 'vsix'
        vsixFile: 'jreleaser-azure-devops-extension.vsix'
        updateTasksVersion: false
    - publish: 'jreleaser-azure-devops-extension.vsix'
      artifact: JReleaserExtension-vsix
    # wait for 1 minute to allow the extension to be installed
    # TODO: find a better way to do this
    - task: CmdLine@2
      displayName: 'wait for 1 minute'
      inputs:
        script: 'sleep 60'