# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.BuildID)

trigger: none

parameters:
- name: version
  displayName: Version
  type: string
  default: ''

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

stages:
- stage: Release
  jobs:
  - job: Release
    steps:
    - checkout: self
      persistCredentials: true
      fetchTags: true
      fetchDepth: 0
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'jreleaser-azure-devops-extension'
        definition: 'Release'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        artifactName: 'JReleaserExtension-vsix'
        targetPath: '$(System.DefaultWorkingDirectory)'
    - task: JReleaserInstaller@0
      inputs:
        version: '1.5.1'
    - task: JReleaserInvoker@0
      env:
        JRELEASER_GITHUB_TOKEN: $(JRELEASER_GITHUB_TOKEN)
        JRELEASER_PROJECT_VERSION: ${{ parameters.version }}
        JRELEASER_TAG_NAME: ${{ parameters.version }}
      inputs:
        command: 'release'
